/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.BankAccountInfo;

/**
 *
 * @author mrudu
 */
public class CheckingAccViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckingAccViewPanel
     */
    BankAccountInfo checkingAcc;
    
    public CheckingAccViewPanel(BankAccountInfo checkingAcc) {
        initComponents();
        this.checkingAcc = checkingAcc;
        
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CheckingAccount = new javax.swing.JLabel();
        BankName = new javax.swing.JLabel();
        RoutingNumber = new javax.swing.JLabel();
        AccNo = new javax.swing.JLabel();
        BankBalance = new javax.swing.JLabel();
        AccType = new javax.swing.JLabel();
        BankNameInput = new javax.swing.JTextField();
        RoutingNumberInput = new javax.swing.JTextField();
        AccNoInput = new javax.swing.JTextField();
        bankBalanceInput = new javax.swing.JTextField();
        accTypeInput = new javax.swing.JTextField();

        CheckingAccount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CheckingAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CheckingAccount.setText("Checking Account Details");

        BankName.setText("Bank Name :");

        RoutingNumber.setText("Bank Routing Number :");

        AccNo.setText("Bank Account Number :");

        BankBalance.setText("Bank Balance :");

        AccType.setText("Account Type :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CheckingAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BankName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RoutingNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AccNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BankBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AccType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(RoutingNumberInput, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BankNameInput, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccNoInput)
                    .addComponent(bankBalanceInput)
                    .addComponent(accTypeInput, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CheckingAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BankNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoutingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoutingNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccNoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bankBalanceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccType, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccNo;
    private javax.swing.JTextField AccNoInput;
    private javax.swing.JLabel AccType;
    private javax.swing.JLabel BankBalance;
    private javax.swing.JLabel BankName;
    private javax.swing.JTextField BankNameInput;
    private javax.swing.JLabel CheckingAccount;
    private javax.swing.JLabel RoutingNumber;
    private javax.swing.JTextField RoutingNumberInput;
    private javax.swing.JTextField accTypeInput;
    private javax.swing.JTextField bankBalanceInput;
    // End of variables declaration//GEN-END:variables

    private void display() {
        
        BankNameInput.setText(checkingAcc.getBankName());
        RoutingNumberInput.setText(checkingAcc.getBankRoutingNo());
        AccNoInput.setText(checkingAcc.getBankAccNo());
        bankBalanceInput.setText(checkingAcc.getBankBalance());
        accTypeInput.setText(checkingAcc.getAccType());
    }
}
