/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.BankAccountInfo;
import model.DemographicInfo;

/**
 *
 * @author mrudu
 */
public class SavingAccCreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form SavingAccCreatePanel
     */
    
    BankAccountInfo acc;
    public String accType;
    DemographicInfo demoInfo;
    
    public SavingAccCreatePanel(DemographicInfo demoInfo, BankAccountInfo acc) {
        initComponents();
        this.demoInfo = demoInfo;
        this.acc = acc;
        this.accType = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SavingAccount = new javax.swing.JLabel();
        BankName = new javax.swing.JLabel();
        RoutingNumber = new javax.swing.JLabel();
        AccNo = new javax.swing.JLabel();
        BankBalance = new javax.swing.JLabel();
        AccType = new javax.swing.JLabel();
        BankNameInput = new javax.swing.JTextField();
        RoutingNumberInput = new javax.swing.JTextField();
        AccNoInput = new javax.swing.JTextField();
        bankBalanceInput = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        SavingAcc = new javax.swing.JRadioButton();
        CheckingAcc = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(246, 229, 251));

        SavingAccount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SavingAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SavingAccount.setText("Input Account Details");

        BankName.setText("Bank Name :");

        RoutingNumber.setText("Bank Routing Number :");

        AccNo.setText("Bank Account Number :");

        BankBalance.setText("Bank Balance :");

        AccType.setText("Account Type :");

        SaveButton.setText("SAVE");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        SavingAcc.setText("Saving Account");
        SavingAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavingAccActionPerformed(evt);
            }
        });

        CheckingAcc.setText("Checking Account");
        CheckingAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckingAccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BankName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RoutingNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AccNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BankBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AccType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(RoutingNumberInput, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                .addComponent(BankNameInput)
                                .addComponent(AccNoInput, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bankBalanceInput, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SavingAcc)
                                .addGap(18, 18, 18)
                                .addComponent(CheckingAcc))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SavingAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SavingAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BankNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoutingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoutingNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccNoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bankBalanceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AccType, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SavingAcc)
                        .addComponent(CheckingAcc)))
                .addGap(18, 18, 18)
                .addComponent(SaveButton)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        
        if(this.accType == "CheckingAcc"){
            acc.setChbankName(BankNameInput.getText());
            acc.setChbankRoutingNo(RoutingNumberInput.getText());
            acc.setChbankAccNo(AccNoInput.getText());
            acc.setChbankBalance(bankBalanceInput.getText());
            acc.setChaccType("Checking");
        }else if(this.accType == "SavingAcc"){
            acc.setBankName(BankNameInput.getText());
            acc.setBankRoutingNo(RoutingNumberInput.getText());
            acc.setBankAccNo(AccNoInput.getText());
            acc.setBankBalance(bankBalanceInput.getText());
            acc.setAccType("Saving");
        }
        demoInfo.setBankAcc(acc);
                
        JOptionPane.showMessageDialog(this, "Information Saved!!");
        
        clearSelection();
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void SavingAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavingAccActionPerformed
        // TODO add your handling code here:
        accType = "SavingAcc";
    }//GEN-LAST:event_SavingAccActionPerformed

    private void CheckingAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckingAccActionPerformed
        // TODO add your handling code here:
        accType = "CheckingAcc";
    }//GEN-LAST:event_CheckingAccActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccNo;
    private javax.swing.JTextField AccNoInput;
    private javax.swing.JLabel AccType;
    private javax.swing.JLabel BankBalance;
    private javax.swing.JLabel BankName;
    private javax.swing.JTextField BankNameInput;
    private javax.swing.JRadioButton CheckingAcc;
    private javax.swing.JLabel RoutingNumber;
    private javax.swing.JTextField RoutingNumberInput;
    private javax.swing.JButton SaveButton;
    private javax.swing.JRadioButton SavingAcc;
    private javax.swing.JLabel SavingAccount;
    private javax.swing.JTextField bankBalanceInput;
    // End of variables declaration//GEN-END:variables

    private void clearSelection() {
        BankNameInput.setText("");
        RoutingNumberInput.setText("");
        AccNoInput.setText("");
        bankBalanceInput.setText("");
        SavingAcc.setSelected(false);
        CheckingAcc.setSelected(false);
    }
}
